apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/quarkus-app

namePrefix: microservice-a-
commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/name: microservice-a

images:
- name: image-name
  newName: {{cookiecutter.image_repo}}/microservice-a
  newTag: "1.0.0"

configMapGenerator:
- literals:
  - QUARKUS_FOOBAR=sample
  name: quarkus-app-envs
