apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/quarkus-app

namePrefix: microservice-a-
commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/name: microservice-a
  foo: vote-app

images:
- name: quarkus-app
  newName: acme.com/repository/microservice-a
  newTag: "1.1.0"

configMapGenerator:
- envs:
  - application.env
  name: quarkus-app-envs