apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/quarkus-app

namePrefix: single-page-app-
commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/name: single-page-app

images:
- name: quarkus-app
  newName: acme.com/repository/single-page-app
  newTag: "1.0.0"

configMapGenerator:
- literals:
  - QUARKUS_FOOBAR=sample
  name: quarkus-app-envs
